version: '3.7'

services:
  zookeeper:
    #image: quay.io/debezium/zookeeper:2.4
    image: bitnami/zookeeper:latest
    network_mode: "host"
    ports:
      - "2181:2181"
    environment:
      - ZOO_ADMIN_SERVER_PORT_NUMBER=8030
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka: 
    image: quay.io/debezium/kafka:2.4
    network_mode: "host"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://localhost:9092,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_LOG_SEGMENT_BYTES=1073741824
      - ZOOKEEPER_CONNECT=127.0.0.1:2181
    depends_on:
      - zookeeper

  kafka-connect:
    image: quay.io/debezium/connect:2.4
    network_mode: "host"
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=127.0.0.1:9092
      - REST_PORT=8083
      - REST_ADVERTISED_HOST_NAME=localhost
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
    depends_on:
      - kafka
      
